databases:
  - name: cinevault-yashvi-db
    plan: free
    databaseName: cinevault
    user: cinevault_user

services:
  - type: web
    name: cinevault-yashvi
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "webapp.backend.app:create_app()" --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cinevault-yashvi-db
          property: connectionString
      - key: TMDB_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: FLASK_DEBUG
        value: "false"
